buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
        mavenCentral()
    }
    dependencies { // Not Published to Gradle Plugin Portal
        classpath "org.grails:grails-gradle-plugin:6.2.4"

    }
}

plugins {
    id "groovy"
    id "war"
    id "idea"
    id "com.bertramlabs.asset-pipeline" version "4.5.1"
    id "application"
    id "eclipse"
}

// Not Published to Gradle Plugin Portal
apply plugin: "org.grails.grails-web"
apply plugin: "org.grails.grails-gsp"

group = "com.example"

ext['spring-security.version'] = '5.8.16'
ext['tomcat.version'] = '9.0.122'
ext['logback.version'] = '1.2.13'
ext['commons-lang3.version'] = '3.20.0'
ext['log4j2.version'] = '2.26.1'

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

dependencies {
    constraints {
        implementation 'commons-fileupload:commons-fileupload:1.6.0'
        implementation 'commons-io:commons-io:2.22.0'
        implementation 'org.apache.commons:commons-lang3:3.20.0'
        implementation 'org.apache.logging.log4j:log4j-api:2.26.1'
    }

    profile "org.grails.profiles:web"
    implementation "org.grails:grails-core"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-interceptors"
    implementation "org.grails:grails-plugin-rest"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails.plugins:gsp"
    implementation "org.grails.plugins:scaffolding"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    compileOnly "io.micronaut:micronaut-inject-groovy"
    console "org.grails:grails-console"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:4.5.1"
    testImplementation "io.micronaut:micronaut-inject-groovy"
    testImplementation "org.grails:grails-gorm-testing-support"
    testImplementation "org.grails:grails-web-testing-support"
    testImplementation "org.spockframework:spock-core"
    implementation "org.grails.plugins:spring-security-core:6.1.2"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.grails.plugins:mongodb"
    implementation "org.mongodb:mongodb-driver-sync"
}

application {
    mainClass = "newspeak.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
}

tasks.withType(Test) {
    useJUnitPlatform()
}
assets {
    minifyJs = true
    minifyCss = true
    skipNonDigests = true
}
