info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

grails:
  mongodb:
    url: mongodb+srv://admin:XCpYPj7qUQgo2Ldn@cluster0.s4ikkos.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none

  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml

  codegen:
    defaultPackage: newspeak
  profile: web

  # Configuración de Spring Security
  plugin:
    springsecurity:
      userLookup:
        userDomainClassName: 'newspeak.User'
        authorityJoinClassName: 'newspeak.UserRole'
      authority:
        className: 'newspeak.Role'
      securityConfigType: "InterceptUrlMap"
      interceptUrlMap:
        - pattern: '/'
          access: ['permitAll']
        - pattern: '/error'
          access: ['permitAll']
        - pattern: '/index'
          access: ['permitAll']
        - pattern: '/login/**'
          access: ['permitAll']
        - pattern: '/j_spring_security_check'
          access: ['permitAll']
        - pattern: '/j_spring_security_logout'
          access: ['permitAll']
        - pattern: '/assets/**'
          access: ['permitAll']
        - pattern: '/**/js/**'
          access: ['permitAll']
        - pattern: '/**/css/**'
          access: ['permitAll']
        - pattern: '/**/images/**'
          access: ['permitAll']
        - pattern: '/**/favicon.ico'
          access: ['permitAll']
        - pattern: '/user/register'
          access: ['permitAll']
        - pattern: '/user/save'
          access: ['permitAll']
        - pattern: '/home/**'
          access: ['ROLE_USER']
        - pattern: '/**'
          access: ['ROLE_USER']
      auth:
        loginFormUrl: '/login/auth'
      failure:
        defaultFailureUrl: '/login/auth?login_error=1'
      logout:
        postOnly: false
        afterLogoutUrl: '/login/auth'
      successHandler:
        defaultTargetUrl: '/home/index'
      password:
        algorithm: 'bcrypt'